type User {
  _id:ID
  username:String!
  email:String!
  password:String!
  avatar:String
  joinDate:String
  favorites:[Post]
}

type Post {
  _id:ID
  title:String!
  imageUrl:String!
  categories:[String]!
  description:String!
  createdDate:String
  likes:Int
  createdBy:User!
  comments:[Comment]
}

type Comment {
  _id:ID
  commentBody:String!
  commentDate:String!
  commentUser:User!
}

type Token {
  token:String!
}

type PostsPage{
  posts:[Post]
  hasMore:Boolean
}

type Query{
  getUsers:[User]
  getUser:User
  getPosts:[Post]
  getPost(postId:ID!):Post
  getCurrentUser:User
  infiniteScrollPosts(pageNum:Int!,pageSize:Int!):PostsPage
}

type Mutation {
  signupUser(username:String!,email:String!,password:String!):Token
  addPost(title:String!,imageUrl:String!,categories:[String]!,description:String,creatorId:ID!):Post!
  signinUser(username:String!,password:String!):Token
  deleteUser(username:String!):User!
  deletePost(_id:ID!):Post!
}