type User {
  _id:ID
  username:String!
  email:String!
  password:String!
  avatar:String
  joinDate:String
  favorites:[Post]
}

type Post {
  _id:ID
  title:String!
  imageUrl:String!
  categories:[String]!
  description:String!
  createdDate:String
  likes:Int
  createdBy:User!
  comments:[Comment]
}

type Comment {
  _id:ID
  commentBody:String!
  commentDate:String!
  commentUser:User!
}

type Query{
  getUsers:[User]
  getUser:User
  getPosts:[Post]
}

type Mutation {
  signupUser(username:String!,email:String!,password:String!):User!
  addPost(title:String!,imageUrl:String!,categories:[String]!,description:String,creatorId:ID!):Post!
  signinUser(username:String!,password:String!):User!
}